//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LA3.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LA3.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The total interest due under this agreement is calculated and added to the sum due at the commencement of this agreement.
        /// </summary>
        internal static string Agreement_Comment01 {
            get {
                return ResourceManager.GetString("Agreement_Comment01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have the right to charge interest at the annual percentage rate shown above, on the overdue amounts (including any balance which may become payable under clause 3) and which remains unpaid at the date for the last payment under this agreement. The interest will be charged on a daily basis from the date the amount falls due until it is received and will run both before and after any Judgement. We may also charge you for any legal costs and other expenses incurred by us in obtaining payment by you of any s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Agreement_Comment02 {
            get {
                return ResourceManager.GetString("Agreement_Comment02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By signing this agreement you agree to repay the loan plus the interest by the payments set out, by their specified dates. Payments must be made to us at the address shown, or to any person or address notified by us in writing.  Punctual payment is essential. If you pay by post you do so at your own risk.  If you already have a loan account with us, the appropriate part of the new loan will be applied in paying off the existing loan, and only the remaining balance will be paid to you.
        ///
        ///2. FAILURE TO PAY O [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Agreement_Terms_and_Conditions {
            get {
                return ResourceManager.GetString("Agreement Terms and Conditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By signing this agreement you agree to repay the loan plus the interest by the payments set out, by their specified dates. Payments must be made to us at the address shown, or to any person or address notified by us in writing.  Punctual payment is essential. If you pay by post you do so at your own risk.  If you already have a loan account with us, the appropriate part of the new loan will be applied in paying off the existing loan, and only the remaining balance will be paid to you.
        ///.
        /// </summary>
        internal static string TestResourceValue {
            get {
                return ResourceManager.GetString("TestResourceValue", resourceCulture);
            }
        }
    }
}
