//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LA3.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.AccountStatusChanges = new HashSet<AccountStatusChange>();
            this.Payments = new HashSet<Payment>();
        }
    
        public int Id { get; set; }
        public System.DateTime StartDate { get; set; }
        public int InvoiceNumber { get; set; }
        public double NetValue { get; set; }
        public double GrossValue { get; set; }
        public int PaymentPeriod { get; set; }
        public bool PayMonthly { get; set; }
        public double Payment { get; set; }
        public System.DateTime LastChecked { get; set; }
        public string Notes { get; set; }
        public System.DateTime NextPaymentDate { get; set; }
        public bool PrintedForm { get; set; }
        public int OldId { get; set; }
        public string LockedByUser { get; set; }
        public int Customer_Id { get; set; }
    
        public virtual ICollection<AccountStatusChange> AccountStatusChanges { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
