//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LA3.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountStatus
    {
        public AccountStatus()
        {
            this.AccountStatusChanges = new HashSet<AccountStatusChange>();
        }
    
        public int Id { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<AccountStatusChange> AccountStatusChanges { get; set; }
    }
}
