//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LA3.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Accounts = new HashSet<Account>();
        }
    
        public int Id { get; set; }
        public string Forename { get; set; }
        public string Surname { get; set; }
        public string Address { get; set; }
        public string PostCode { get; set; }
        public string Notes { get; set; }
        public int PreferredDay { get; set; }
        public int Maxloan { get; set; }
        public string PhoneNumber { get; set; }
        public System.DateTime StartDate { get; set; }
        public bool Locked { get; set; }
        public bool IsDeleted { get; set; }
        public string LockedByUser { get; set; }
        public int Collector_Id { get; set; }
        public int OldId { get; set; }
    
        public virtual ICollection<Account> Accounts { get; set; }
        public virtual Collector Collector { get; set; }
    }
}
