//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LA3.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int Id { get; set; }
        public System.DateTime Timestamp { get; set; }
        public double Amount { get; set; }
        public string Note { get; set; }
        public bool IsSundry { get; set; }
        public int PaidByAccountId { get; set; }
        public int Account_Id { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
